kind: Pod
apiVersion: v1
metadata:
  name: newsapp-pod
  labels:
    app: newsapp
spec:
  containers:
  - name: golang-news-app
    image: {{ .Values.imageName }}:{{ .Values.appVersion }}
    ports:
     - name: app-ui-port
       containerPort: 9003
